config/routes.rb
Rails.application.routes.draw do
  resources :carnets
  resources :nutritional_controls
  resources :aliments
       # Serve websocket cable requests in-process
   mount ActionCable.server => '/cable' 
  get 'rooms/show'

  resources :cow_histories
  resources :arduino_devices do 
    get "get_report"
    get "get_last_moves_x"
    get "get_last_moves_y"
    get "get_last_moves_z"
    match 'search' => 'arduino_devices#search', via: [:get, :post], as: :search
    get "get_last_moves"
     
  end
  resources :farms
  resources :cows do
      get "delete"
      collection do
      get 'filter'
    end
  end
  resources :veterinaries do
      get "delete"
      collection do
      get 'filter'
    end
  end
  resources :roles
   devise_for :users
   get 'welcome/index'
  namespace :admin do
    resources :users do
      get "delete"
      collection do
      get 'filter'
    end
    end
  end	
  root 'welcome#index'

  namespace :api do 
    resources :cow_histories
  end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aliment.rb
class Aliment < ApplicationRecord
	has_many :nutritional_control_has_aliments
	has_many :nutritional_control, through: :nutritional_control_has_aliments 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arduino_device.rb
class ArduinoDevice < ApplicationRecord
	belongs_to :user
	belongs_to :cow  
	has_many :cow_histories 

	  scope :created_on, lambda {|date| {:conditions => ['created_at >= ? AND created_at <= ?', date.beginning_of_day, date.end_of_day]}}

  def self.today
    self.created_on(Date.today)
  end
end

app/models/carnet.rb
class Carnet < ApplicationRecord
	belongs_to :cow
end

app/models/cow.rb
class Cow < ApplicationRecord
	has_many :cow_histories
	has_many :arduino_devices
	has_one :carnet
end

app/models/cow_history.rb
class CowHistory < ApplicationRecord
    belongs_to :arduino_device
	belongs_to :cow 

scope :today, -> { where(created_at: DateTime.now.beginning_of_day..DateTime.now.end_of_day) }


end

app/models/farm.rb
class Farm < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
	after_create_commit { MessageBroadcastJob.perform_later self }
	
end

app/models/nutritional_control.rb
class NutritionalControl < ApplicationRecord
	 
	has_many :nutritional_control_has_aliments
	has_many :aliments , through: :nutritional_control_has_aliments 
end

app/models/role.rb
class Role < ApplicationRecord
has_many :users

scope :veterinary, -> { where(rol_name: 'veterinario').limit(1).pluck(:id).first }
 scope :for_user, -> { limit(2) }
end

app/models/user.rb
class User < ApplicationRecord 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :arduino_devices
  acts_as_token_authenticatable
 devise :database_authenticatable, :rememberable, :trackable, :validatable
   has_one :veterinary
   belongs_to :role  
   before_validation :erase , on: :delete   
  def erase 
    soft_delete
  end 
  def full_name
    self.name + " " + self.lastname
  end
  def inactive_message
    !deleted_at ? super : :deleted_account
  end
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end
end

app/models/veterinary.rb
class Veterinary < ApplicationRecord 
	 belongs_to :user
	 accepts_nested_attributes_for :user, allow_destroy: true

	 



	 
end

app/controllers/aliments_controller.rb
class AlimentsController < ApplicationController
  before_action :set_aliment, only: [:show, :edit, :update, :destroy]

  # GET /aliments
  # GET /aliments.json
  def index
    @aliments = Aliment.all
  end

  # GET /aliments/1
  # GET /aliments/1.json
  def show
  end

  # GET /aliments/new
  def new
    @aliment = Aliment.new
  end

  # GET /aliments/1/edit
  def edit
  end

  # POST /aliments
  # POST /aliments.json
  def create
    @aliment = Aliment.new(aliment_params)

    respond_to do |format|
      if @aliment.save
        format.html { redirect_to @aliment, notice: 'Aliment was successfully created.' }
        format.json { render :show, status: :created, location: @aliment }
      else
        format.html { render :new }
        format.json { render json: @aliment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aliments/1
  # PATCH/PUT /aliments/1.json
  def update
    respond_to do |format|
      if @aliment.update(aliment_params)
        format.html { redirect_to @aliment, notice: 'Aliment was successfully updated.' }
        format.json { render :show, status: :ok, location: @aliment }
      else
        format.html { render :edit }
        format.json { render json: @aliment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aliments/1
  # DELETE /aliments/1.json
  def destroy
    @aliment.destroy
    respond_to do |format|
      format.html { redirect_to aliments_url, notice: 'Aliment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aliment
      @aliment = Aliment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def aliment_params
      params.require(:aliment).permit(:name)
    end
end

app/controllers/cows_controller.rb
class CowsController < ApplicationController
  before_action :set_cow, only: [:show, :edit, :update, :destroy]

    def index
    search
  end
  
  # GET /cows/1
  # GET /cows/1.json
  def show
    @cow = Cow.find(params[:id])

  end

  # GET /cows/new
  def new
    @cow = Cow.new  
    respond_to do |format| 
      format.js if request.xhr?
      format.html { redirect_to :action => "index"}
    end
  end
  def delete
    @cow = Cow.find(params[:cow_id])
  end
  # GET /cows/1/edit
  def edit
  end

  # POST /cows
  # POST /cows.json
  def create
    

    @cow = Cow.new(cow_params) 
    @cow.save
    search
  end

  # PATCH/PUT /cows/1
  # PATCH/PUT /cows/1.json
  def update
   respond_to do |format|
    if @cow.update(cow_params)
      search
      format.html { redirect_to @cow, notice: 'cow was successfully updated.' }
      format.json { render :show, status: :ok, location: @cow }
      format.js
    else
      format.html { render :edit }
      format.json { render json: @cow.errors, status: :unprocessable_entity }
      format.js
    end
  end
end



def destroy 
  @cow.destroy
  respond_to do |format|
    format.html { redirect_to cows_url, notice: 'cow was successfully destroyed.' }
    format.json { head :no_content }
  end
end

def search(per_page = 10)
  params[:q] ||= {}
  params[:per_page] = 10
  @q = Cow.ransack(params[:q])
  @cows =  @q.result(distinct: true).page(params[:page]).per(params[:per_page])
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cow
      @cow = Cow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cow_params
      params.require(:cow).permit(:key_id, :name, :birthday, :deaddate, :deleted_at)
    end
end

app/helpers/aliments_helper.rb
module AlimentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carnets_helper.rb
module CarnetsHelper
end

app/helpers/cows_helper.rb
module CowsHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/veterinaries_helper.rb
module VeterinariesHelper
	def setup_veterinary(veterinary)
    veterinary.user ||= User.new
    veterinary
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/aliments/_form.html.erb
<%= form_with(model: aliment, local: true) do |form| %>
  <% if aliment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(aliment.errors.count, "error") %> prohibited this aliment from being saved:</h2>

      <ul>
      <% aliment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :aliment_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/aliments/edit.html.erb
<h1>Editing Aliment</h1>

<%= render 'form', aliment: @aliment %>

<%= link_to 'Show', @aliment %> |
<%= link_to 'Back', aliments_path %>

app/views/aliments/index.html.erb
 
<div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="header">
                                <h4 class="title">Control Nutricional</h4>
                                <p class="category"><%= notice %></p>
                            </div>
                            <div class="content table-responsive table-full-width">
                                <table class="table table-hover table-striped">
                                  <thead>
                                    <tr>
                                      <th>Name</th>
                                      <th colspan="3"></th>
                                    </tr>
                                  </thead>
                                <tbody>
                                  <% @aliments.each do |aliment| %>
                                    <tr>
                                      <td><%= aliment.name %></td>
                                      <td><%= link_to 'Show', aliment %></td>
                                      <td><%= link_to 'Edit', edit_aliment_path(aliment) %></td>
                                      <td><%= link_to 'Destroy', aliment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                    </tr>
                                  <% end %>
                                </tbody>                                
                              </table>
                              <%= link_to 'New Aliment', new_aliment_path %>
                            </div>
                        </div>
                    </div>

          
               

                </div>

app/views/aliments/new.html.erb
<h1>New Aliment</h1>

<%= render 'form', aliment: @aliment %>

<%= link_to 'Back', aliments_path %>

app/views/aliments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @aliment.name %>
</p>

<%= link_to 'Edit', edit_aliment_path(@aliment) %> |
<%= link_to 'Back', aliments_path %>