config/routes.rb
Rails.application.routes.draw do
  resources :carnets
  resources :nutritional_controls
  resources :aliments
       # Serve websocket cable requests in-process
   mount ActionCable.server => '/cable' 
  get 'rooms/show'

  resources :cow_histories
  resources :arduino_devices do 
    get "get_report"
    get "get_last_moves_x"
    get "get_last_moves_y"
    get "get_last_moves_z"
    match 'search' => 'arduino_devices#search', via: [:get, :post], as: :search
    get "get_last_moves"
     
  end
  resources :farms
  resources :cows do
      get "delete"
      collection do
      get 'filter'
    end
  end
  resources :veterinaries do
      get "delete"
      collection do
      get 'filter'
    end
  end
  resources :roles
   devise_for :users
   get 'welcome/index'
  namespace :admin do
    resources :users do
      get "delete"
      collection do
      get 'filter'
    end
    end
  end	
  root 'welcome#index'

  namespace :api do 
    resources :cow_histories
  end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/arduino_device.rb
class ArduinoDevice < ApplicationRecord
	belongs_to :user
	belongs_to :cow  
	has_many :cow_histories 

	  scope :created_on, lambda {|date| {:conditions => ['created_at >= ? AND created_at <= ?', date.beginning_of_day, date.end_of_day]}}

  def self.today
    self.created_on(Date.today)
  end
end

app/controllers/arduino_devices_controller.rb
class ArduinoDevicesController < ApplicationController
  before_action :set_arduino_device, only: [:show, :edit, :update, :destroy  ]
   skip_before_action :authenticate_user!, :only => [:show]
  # GET /arduino_devices
  # GET /arduino_devices.json
  def index
    @arduino_devices = ArduinoDevice.all
  end
  def search
    @arduino_device = ArduinoDevice.find(params[:arduino_device_id])
    show
    render :show
  end
  # GET /arduino_devices/1
  # GET /arduino_devices/1.json
  def show
     
    

    params[:q] ||= {}
    params[:q][:created_at]= Date.today unless params[:q][:created_at] 
    @q = @arduino_device.cow_histories.search(params[:q])
    @current_date= params[:q][:created_at]
    load_moves

  end
  def get_report
    
    # @arduino_device = ArduinoDevice.find(params[:arduino_device_id]) 
    # params[:q] ||= {}
    # params[:q][:created_at]= Date.today unless params[:q][:created_at] 
    # @q = @arduino_device.cow_histories.search(params[:q])
    # @current_date= params[:q][:created_at]
    # load_moves
    # respond_to do |format|
    #   format.html
    #   format.pdf do
    #     render pdf: "get_report" ,javascript_delay: 5000   # Excluding ".pdf" extension.
    #   end
    # end
  end
  def set_date
    @current_date = params[:current_date]
  end

  def get_last_moves_x  


    @arduino_device = ArduinoDevice.find(params[:arduino_device_id])  
 

    render json:  @arduino_device.cow_histories.where("cow_histories.created_at>=?", params[:current_date]  ).pluck(:created_at,:x ).last(100) 
  end 


  def get_last_moves
    @arduino_device = ArduinoDevice.find(params[:arduino_device_id]) 
    set_date
   load_moves
    render :layout => false
  end 
 def load_moves
    @caminando=0
    @parada=0
    @sentada=0
    @dormida=0

    @total='' 
   
    @arduino_device.cow_histories.where("cow_histories.created_at>=?", @current_date ).each_with_index do |cow_historie, index|
      
      if @last_hist  
        @is_moving =false
        diference_movement = cow_historie.y.to_f -  @last_hist.y.to_f  
        @is_moving =true if diference_movement>5||diference_movement<-5 
        diference = cow_historie.z.to_f -  @last_hist.z.to_f 
        @direccion=""
        @direccion= "  hacia la derecha  "   if diference < -500
        @direccion=" hacia la  izquierda  "  if diference > 500 
       #@total+= "<br>La vaca esta caminando"+@direccion+", Fecha:"+cow_historie.created_at.utc.to_s if @is_moving
        if ((diference < -500)||(diference > 500))&&@is_moving
          created = @last_hist.created_at 
          updated = cow_historie.created_at  
          @caminando+= ((updated - created)  ).to_f if (((updated - created) ))<100 
          @current_state="cowwalking.gif"
       end
        if (70..90).include?(cow_historie.x.to_f)&&(-10..15).include?(cow_historie.y.to_f)&&(70..90).include?(@last_hist.x.to_f)&&(-10..15).include?(@last_hist.y.to_f)&&!@is_moving
          created = @last_hist.created_at
          updated = cow_historie.created_at 
          @parada+= ((updated - created) ).to_f if (((updated - created) ))<100
          @current_state="vacas_parada.gif"
       end
       #@total+= "<br>La vaca esta parada/quieta, Fecha:"+cow_historie.created_at.utc.to_s if (70..90).include?(cow_historie.x.to_f)&&(-10..15).include?(cow_historie.y.to_f)&&(70..90).include?(@last_hist.x.to_f)&&(-10..15).include?(@last_hist.y.to_f)&&!@is_moving
       #
       if (-20..19).include?(cow_historie.x.to_f)&&(-90..-63).include?(cow_historie.y.to_f)&&(-20..19).include?(@last_hist.x.to_f)&&(-90..-63).include?(@last_hist.y.to_f)
          created = @last_hist.created_at
          updated = cow_historie.created_at 
          @sentada+= ((updated - created) ).to_f if (((updated - created) ))<100
          @current_state="vaca_acostada.jpg"
       end
       #@total+= "<br>La vaca esta sentada, Fecha:"+cow_historie.created_at.utc.to_s if (-20..19).include?(cow_historie.x.to_f)&&(-90..-63).include?(cow_historie.y.to_f)&&(-20..19).include?(@last_hist.x.to_f)&&(-90..-63).include?(@last_hist.y.to_f)
      
       if (15..27).include?(cow_historie.x.to_f)&&(0..31).include?(cow_historie.y.to_f)&&(15..27).include?(@last_hist.x.to_f)&&(0..31).include?(@last_hist.y.to_f)        
          created = @last_hist.created_at 
          updated = cow_historie.created_at   
          @dormida+= ((updated - created) ).to_f if (((updated - created) ))<100 
          @current_state="vaca_durmiendo.jpg" 
       end
       #@total+= "<br>La vaca esta durmiendo, Fecha:"+cow_historie.created_at.utc.to_s if (15..27).include?(cow_historie.x.to_f)&&(0..31).include?(cow_historie.y.to_f)&&(15..27).include?(@last_hist.x.to_f)&&(0..31).include?(@last_hist.y.to_f) 
      end  
      @last_hist = cow_historie 
    end 
    
  end 
   def get_cow_state

    @total=''

    @arduino_device = ArduinoDevice.find(params[:arduino_device_id]) 
   
    @arduino_device.cow_histories.where("cow_histories.created_at>=?", params[:current_date] ).last(50).each_with_index do |cow_historie, index|
        
        
         cow_historie.x.to_f  
       
       
     
    end  
  end 

  def get_last_moves_y  

     @arduino_device = ArduinoDevice.find(params[:arduino_device_id])
      
     
    render json:  @arduino_device.cow_histories.where("cow_histories.created_at>=?", params[:current_date] ).pluck(:created_at,:y ).last(100) 
  end  
  def get_last_moves_z  

     @arduino_device = ArduinoDevice.find(params[:arduino_device_id])
     
    render json:  @arduino_device.cow_histories.where("cow_histories.created_at>=?", params[:current_date]  ).pluck(:created_at,:z ).last(100) 
  end  
  # GET /arduino_devices/new
  def new
    @arduino_device = ArduinoDevice.new
  end

  # GET /arduino_devices/1/edit
  def edit
  end

  # POST /arduino_devices
  # POST /arduino_devices.json
  def create 

    respond_to do |format|
      if current_user.arduino_devices.create(arduino_device_params)
        format.html { redirect_to arduino_devices_url, notice: 'Arduino device was successfully created.' }
        format.json { render :show, status: :created, location: @arduino_device }
      else
        format.html { render :new }
        format.json { render json: @arduino_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arduino_devices/1
  # PATCH/PUT /arduino_devices/1.json
  def update
    respond_to do |format|
      if @arduino_device.update(arduino_device_params)
        format.html { redirect_to @arduino_device, notice: 'Arduino device was successfully updated.' }
        format.json { render :show, status: :ok, location: @arduino_device }
      else
        format.html { render :edit }
        format.json { render json: @arduino_device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arduino_devices/1
  # DELETE /arduino_devices/1.json
  def destroy
    @arduino_device.destroy
    respond_to do |format|
      format.html { redirect_to arduino_devices_url, notice: 'Arduino device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_arduino_device
      @arduino_device = ArduinoDevice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def arduino_device_params
      params.require(:arduino_device).permit(:chipid, :model, :cow_id)
    end
end

app/helpers/arduino_devices_helper.rb
module ArduinoDevicesHelper
end

app/views/arduino_devices/_form.html.erb
<%= form_with(model: arduino_device, local: true) do |form| %>
  <% if arduino_device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(arduino_device.errors.count, "error") %> prohibited this arduino_device from being saved:</h2>

      <ul>
      <% arduino_device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

  <div class="field">
    <%= form.label :chipid %>
    <%= form.text_field :chipid, id: :arduino_device_chipid %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :arduino_device_model %>
  </div>
  <div class="field">
    <%= form.label :cow %>
   <%=form.collection_select :cow_id, Cow.where("deleted_at IS NULL"), :id, :name, {prompt: 'Selecciona...'}, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/arduino_devices/edit.html.erb
<h1>Editing Arduino Device</h1>

<%= render 'form', arduino_device: @arduino_device %>

<%= link_to 'Show', @arduino_device %> |
<%= link_to 'Back', arduino_devices_path %>

app/views/arduino_devices/get_last_moves.html.erb
<%#= @total.html_safe %>

<div class="col-md-6">
  <div class="card" >

    <div class="header">
      <h4 class="title"><i class="pe-7s-signal"></i>Balance de comportamiento</h4>
      
    </div> 
    <div class="content">  

     <div id="donut" style="height: 300px;"></div> 
     
     <script>
      new Chartkick.PieChart("donut", [["Caminando ",<%=(@caminando/60).to_i.to_s%>],["Sueño",<%=(@dormida/60).to_i.to_s.to_s%> ],["parada",<%=(@parada/60).to_i.to_s%>],["Sentada ", <%=(@sentada/60).to_i.to_s%>]],{download: "donut"});
    </script>
  </div>
  
</div>
</div>
<div class="col-md-3">
  <div class="card" >

    <div class="header">
      <h4 class="title"><i class="pe-7s-clock"></i> Tiempo de Actividad (en Minutos)</h4>

    </div> 
    <div class="content"> 
      <ul>
        <li>Tiempo Total Caminando:
        <%= (@caminando/60).to_i.to_s %> Minutos
        (Normal debe ser aproximadamente 240)</li>
        <li>
        Tiempo Total de Pie:
        <%= (@parada/60).to_i.to_s %> Minutos </li>
        <li>
        Tiempo Total de Sentada:
        <%= (@sentada/60).to_i.to_s %> Minutos
        (Normal debe ser entre 720-600)</li>
        <li>
        Tiempo Total de Sueño:
        <%= (@dormida/60 ).to_i.to_s %> Minutos
        (Normal debe ser entre 300-200)</li>
      </ul>
 
      </div>

    </div>
  </div>   



  <div class="col-md-3">
    <div class="card" >

      <div class="header">
        <h4 class="title"><i class="pe-7s-signal"></i>Ultimo estado </h4>

      </div> 
      <div class="content"> 



       <%= image_tag(@current_state,   alt: @current_state,   height: '130px') if @current_state%> 
     </div>

   </div>
 </div>   



 <div class="col-md-4">
  <div class="card" >

    <div class="header">
      <h4 class="title"><i class="pe-7s-signal"></i>Sueño</h4>

    </div> 
    <div class="content">   


    
            <%= column_chart [{"name":"Minutos","data":[ 
              ["Sueño",(@dormida/60).to_i.to_s] ]},
              {"name":"Minutos en Promedio","data":[  
                ["Sueño",300] 
                ]}] %>

              </div>
              
            </div>
          </div>
 <div class="col-md-4">
  <div class="card" >

    <div class="header">
      <h4 class="title"><i class="pe-7s-signal"></i>Sentada</h4>

    </div> 
    <div class="content">   


     
        <%= column_chart [{"name":"Minutos","data":[ 
          ["Sentada ",(@sentada/60).to_i.to_s] ]},
          {"name":"Minutos en Promedio","data":[ 

            ["Sentada ",720] 
            ]}] %>
 

              </div>
              
            </div>
          </div>
 <div class="col-md-4">
  <div class="card" >

    <div class="header">
      <h4 class="title"><i class="pe-7s-signal"></i>Caminando</h4>

    </div> 
    <div class="content">   


      <%= column_chart [{"name":"Minutos","data":[["Caminando ",(@caminando/60).to_i.to_s] ]},
      {"name":"Minutos en Promedio","data":[ 
        ["Caminando ",240] 
        ]}] %>

 >

              </div>
              
            </div>
          </div>

app/views/arduino_devices/get_report.pdf.erb
<!DOCTYPE html>
<html>
<head>
	<title>PDF report</title> 
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/chartkick/2.2.4/chartkick.min.js"></script>
  <meta charset="utf-8" />
</head>
<body>
<div class="row">  

  <div id="target-1" class="span12">

 


      <h1>Detalles</h1>


      <p id="notice"><%= notice %></p>
      <button onclick="delayPrint()">Imprimir Reporte</button>
      <%= search_form_for @q, url: arduino_device_search_path(@arduino_device),
      html: { method: :post } do |f| %>

      <br> 
      <div class="span12">
        <%= f.label :created_at,"Fecha", class: "control-label span1" %>
        <div class="span3">
          <%= f.text_field :created_at, type: "date", class: "form-control", value: @current_date if @current_date %>
        </div>

      </div> 


      <%= f.submit t('search') , :class => "btn btn-success" %>

      <% end %>
      <div id='section-to-print'>
        <div class="row">
          <i class="icon-list-alt"></i>
            <h1>Datos del Bovino</h1>
           

          <p>
            <strong>Chipid:</strong>
            <%= @arduino_device.chipid %>
          </p>

          <p>
            <strong>Model:</strong>
            <%= @arduino_device.model %>
          </p>

          <p>
            <strong>Usuario:</strong>
            <%= @arduino_device.user.name %>
          </p>

          <p>
            <strong>ID de Bovino:</strong>
            <%= @arduino_device.cow.id %>
          </p>  
            <div class="span12"> 
              <h1>Tiempo de Actividad (en Minutos)</h1>
              <div id="msn">
              	<div class="span12">
				<div class="span7">
				<p>Tiempo Total Caminando:
				<%= (@caminando/60).to_i.to_s %> Minutos
				(Normal debe ser aproximadamente 240)
				<br>
				Tiempo Total de Pie:
				<%= (@parada/60).to_i.to_s %> Minutos  
				<br>
				Tiempo Total de Sentada:
				<%= (@sentada/60).to_i.to_s %> Minutos
				(Normal debe ser entre 720-600)
				<br>
				Tiempo Total de Sueño:
				<%= (@dormida/60 ).to_i.to_s %> Minutos
				(Normal debe ser entre 300-200)
				<br></p>
				</div>
				<div class="span3">
				<p>Ultimo estado: </p>
				<br>
				<%= wicked_pdf_image_tag(@current_state,   alt: @current_state) if @current_state%>   
				</div>
				</div>
                  <!-- .stat --> 
                </div>

           
           </div>
           
 
        <h1>Comparativo con el tiempo promedio de un bovino sano</h1>
        <div class="span4">
          <%= column_chart [{"name":"Minutos","data":[["Caminando ",(@caminando/60).to_i.to_s] ]},
          {"name":"Minutos en Promedio","data":[ 
            ["Caminando ",240] 
            ]}] %>
          </div>
          <div class="span4">
            <%= column_chart [{"name":"Minutos","data":[ 
              ["Sentada ",(@sentada/60).to_i.to_s] ]},
              {"name":"Minutos en Promedio","data":[ 

                ["Sentada ",720] 
                ]}] %>
              </div>
              <div class="span4">
                <%= column_chart [{"name":"Minutos","data":[ 
                  ["Sueño",(@dormida/60).to_i.to_s] ]},
                  {"name":"Minutos en Promedio","data":[  
                    ["Sueño",300] 
                    ]}] %>
                  </div>



                </div>
                



             
            </div>

          

        </div> <!-- /widget -->

      </div> <!-- /span12 --> 
     
 
</body>
</html>

app/views/arduino_devices/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
      <div class="header">
        <h4 class="title"><i class="pe-7s-signal"></i> Mis arduinos</h4>
        <p class="category"><%= notice %></p>
      </div>
      <div class="content  ">
        <i class="fa fa-plus"></i> <%= link_to 'New Arduino Device', new_arduino_device_path %>
        <table class="table table-hover table-striped"> 
          <thead>
            <tr>
              <th>Chipid</th>
              <th>Model</th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @arduino_devices.each do |arduino_device| %>
            <tr>
              <td><%= arduino_device.chipid %></td>
              <td><%= arduino_device.model %></td>
              <td><%= link_to 'Show', arduino_device_url(arduino_device ) %></td>
              
              <td><%= link_to 'Edit', edit_arduino_device_path(arduino_device) %></td>
              <td><%= link_to 'Destroy', arduino_device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
            <% end %>
          </tbody>
        </table>

        <div class="footer">
         
          <div class="stats">
           
          </div>
        </div>
        
      </div>

    </div>

  </div>
</div>

app/views/arduino_devices/new.html.erb
<h1>New Arduino Device</h1>

<%= render 'form', arduino_device: @arduino_device %>

<%= link_to 'Back', arduino_devices_path %>

app/views/arduino_devices/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="card">
  
      <div class="header">
        <h4 class="title"><i class="pe-7s-signal"></i> Detalles</h4>
        <p class="category"><%= notice %></p>
      </div>
 

      <div class="content  ">
      <button onclick="delayPrint()">Imprimir Reporte</button>
      <%= search_form_for @q, url: arduino_device_search_path(@arduino_device),
      html: { method: :post } do |f| %>

      <br> 
      <div class="span12">
        <%= f.label :created_at,"Fecha", class: "control-label span1" %>
        <div class="span3">
          <%= f.text_field :created_at, type: "date", class: "form-control", value: @current_date if @current_date %>
        </div>

      </div> 


      <%= f.submit t('search') , :class => "btn btn-success" %>

      <% end %>
    </div> <!-- /widget -->
     </div> 
    </div> <!-- /span12 --> 
 </div> 
 <div class="row" id='section-to-print'>
  <div class="col-md-12">
    <div class="card" >
  
      <div class="header">
        <h4 class="title"><i class="pe-7s-signal"></i> Datos del Bovino</h4>
       
      </div> 
        <div class="content"> 
             
            <p>
               <strong>Fecha:</strong>
             <%= @current_date %></p>

          <p>
            <strong>Chipid:</strong>
            <%= @arduino_device.chipid %>
          </p>

          <p>
            <strong>Model:</strong>
            <%= @arduino_device.model %>
          </p>

          <p>
            <strong>Usuario:</strong>
            <%= @arduino_device.user.name %>
          </p>

          <p>
            <strong>ID de Bovino:</strong>
            <%= @arduino_device.cow.id %>
          </p>   


 
           
 
      



                </div>
                


 
            </div>
        </div>  
    <div id="msn">Cargando...
                 
    </div>
   </div>       

        

<script>
  function delayPrint() { 
    window.print(); 
  } 

    setInterval(function(){ 
     $.ajax({url: "/arduino_devices/<%=@arduino_device.id%>/get_last_moves?current_date=<%=@current_date%>", success: function(result){

      $("#msn").html(result);
    }});

   }, 3000); 
</script>