config/routes.rb
Rails.application.routes.draw do
  resources :carnets
  resources :nutritional_controls
  resources :aliments
       # Serve websocket cable requests in-process
   mount ActionCable.server => '/cable' 
  get 'rooms/show'

  resources :cow_histories
  resources :arduino_devices do 
    get "get_report"
    get "get_last_moves_x"
    get "get_last_moves_y"
    get "get_last_moves_z"
    match 'search' => 'arduino_devices#search', via: [:get, :post], as: :search
    get "get_last_moves"
     
  end
  resources :farms
  resources :cows do
      get "delete"
      collection do
      get 'filter'
    end
  end
  resources :veterinaries do
      get "delete"
      collection do
      get 'filter'
    end
  end
  resources :roles
   devise_for :users
   get 'welcome/index'
  namespace :admin do
    resources :users do
      get "delete"
      collection do
      get 'filter'
    end
    end
  end	
  root 'welcome#index'

  namespace :api do 
    resources :cow_histories
  end
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/aliment.rb
class Aliment < ApplicationRecord
	has_many :nutritional_control_has_aliments
	has_many :nutritional_control, through: :nutritional_control_has_aliments 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/arduino_device.rb
class ArduinoDevice < ApplicationRecord
	belongs_to :user
	belongs_to :cow  
	has_many :cow_histories 

	  scope :created_on, lambda {|date| {:conditions => ['created_at >= ? AND created_at <= ?', date.beginning_of_day, date.end_of_day]}}

  def self.today
    self.created_on(Date.today)
  end
end

app/models/carnet.rb
class Carnet < ApplicationRecord
	belongs_to :cow
end

app/models/cow.rb
class Cow < ApplicationRecord
	has_many :cow_histories
	has_many :arduino_devices
	has_one :carnet
end

app/models/cow_history.rb
class CowHistory < ApplicationRecord
    belongs_to :arduino_device
	belongs_to :cow 

scope :today, -> { where(created_at: DateTime.now.beginning_of_day..DateTime.now.end_of_day) }


end

app/models/farm.rb
class Farm < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
	after_create_commit { MessageBroadcastJob.perform_later self }
	
end

app/models/nutritional_control.rb
class NutritionalControl < ApplicationRecord
	 
	has_many :nutritional_control_has_aliments
	has_many :aliments , through: :nutritional_control_has_aliments 
end

app/models/role.rb
class Role < ApplicationRecord
has_many :users

scope :veterinary, -> { where(rol_name: 'veterinario').limit(1).pluck(:id).first }
 scope :for_user, -> { limit(2) }
end

app/models/user.rb
class User < ApplicationRecord 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :arduino_devices
  acts_as_token_authenticatable
 devise :database_authenticatable, :rememberable, :trackable, :validatable
   has_one :veterinary
   belongs_to :role  
   before_validation :erase , on: :delete   
  def erase 
    soft_delete
  end 
  def full_name
    self.name + " " + self.lastname
  end
  def inactive_message
    !deleted_at ? super : :deleted_account
  end
  def soft_delete
    update_attribute(:deleted_at, Time.current)
  end
end

app/models/veterinary.rb
class Veterinary < ApplicationRecord 
	 belongs_to :user
	 accepts_nested_attributes_for :user, allow_destroy: true

	 



	 
end

app/controllers/cows_controller.rb
class CowsController < ApplicationController
  before_action :set_cow, only: [:show, :edit, :update, :destroy]

    def index
    search
  end
  
  # GET /cows/1
  # GET /cows/1.json
  def show
    @cow = Cow.find(params[:id])

  end

  # GET /cows/new
  def new
    @cow = Cow.new  
    respond_to do |format| 
      format.js if request.xhr?
      format.html { redirect_to :action => "index"}
    end
  end
  def delete
    @cow = Cow.find(params[:cow_id])
  end
  # GET /cows/1/edit
  def edit
  end

  # POST /cows
  # POST /cows.json
  def create
    

    @cow = Cow.new(cow_params) 
    @cow.save
    search
  end

  # PATCH/PUT /cows/1
  # PATCH/PUT /cows/1.json
  def update
   respond_to do |format|
    if @cow.update(cow_params)
      search
      format.html { redirect_to @cow, notice: 'cow was successfully updated.' }
      format.json { render :show, status: :ok, location: @cow }
      format.js
    else
      format.html { render :edit }
      format.json { render json: @cow.errors, status: :unprocessable_entity }
      format.js
    end
  end
end



def destroy 
  @cow.destroy
  respond_to do |format|
    format.html { redirect_to cows_url, notice: 'cow was successfully destroyed.' }
    format.json { head :no_content }
  end
end

def search(per_page = 10)
  params[:q] ||= {}
  params[:per_page] = 10
  @q = Cow.ransack(params[:q])
  @cows =  @q.result(distinct: true).page(params[:page]).per(params[:per_page])
end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cow
      @cow = Cow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cow_params
      params.require(:cow).permit(:key_id, :name, :birthday, :deaddate, :deleted_at)
    end
end

app/controllers/veterinaries_controller.rb
class VeterinariesController < ApplicationController
   
   before_action :set_veterinary, only: [:show, :edit, :update, :destroy]
 # GET /veterinarys
  # GET /veterinarys.json
  def index
    search
  end
  
  # GET /veterinarys/1
  # GET /veterinarys/1.json
  def show
    @veterinary = Veterinary.find(params[:id])

  end

  # GET /veterinarys/new
  def new
    @veterinary = Veterinary.new
    @veterinary.build_user
   
    respond_to do |format|
      #if request.xhr?
       # format.html
      #else
       # format.html { redirect_to customers_url, notice: 'Access denied via url.' }
      #end
      format.js if request.xhr?
      format.html { redirect_to :action => "index"}
    end
  end
  def delete
    @veterinary = Veterinary.find(params[:veterinary_id])
  end
  # GET /veterinarys/1/edit
  def edit
  end

  # POST /veterinarys
  # POST /veterinarys.json
  def create
    search

    @veterinary = Veterinary.new(veterinary_params)
    
    @veterinary.user.role_id = Role.veterinary
    puts Role.veterinary
    puts @veterinary.user.role_id
    @veterinary.save
  end

  # PATCH/PUT /veterinarys/1
  # PATCH/PUT /veterinarys/1.json
  def update
   respond_to do |format|
    if @veterinary.update(veterinary_params)
      search
      format.html { redirect_to @veterinary, notice: 'veterinary was successfully updated.' }
      format.json { render :show, status: :ok, location: @veterinary }
      format.js
    else
      format.html { render :edit }
      format.json { render json: @veterinary.errors, status: :unprocessable_entity }
      format.js
    end
  end
end



def destroy
  user =  User.find(@veterinary.user_id)
  @veterinary.destroy
  user.save!(context: :delete) 
  respond_to do |format|
    format.html { redirect_to veterinaries_url, notice: 'veterinary was successfully destroyed.' }
    format.json { head :no_content }
  end
end

def search(per_page = 10)
  params[:q] ||= {}
  params[:per_page] = 10
  @q = Veterinary.ransack(params[:q])
  @veterinaries =  @q.result(distinct: true).page(params[:page]).per(params[:per_page])
end
 
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veterinary
      @veterinary = Veterinary.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def veterinary_params
      params.require(:veterinary).permit(:clinic, :phone, :web_site, :address, user_attributes:[ :id, :email, :password, :password_confirmation, :name, :lastname, :role_id])
    end
end 

 

app/helpers/aliments_helper.rb
module AlimentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carnets_helper.rb
module CarnetsHelper
end

app/helpers/cows_helper.rb
module CowsHelper
end

app/helpers/farms_helper.rb
module FarmsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/veterinaries_helper.rb
module VeterinariesHelper
	def setup_veterinary(veterinary)
    veterinary.user ||= User.new
    veterinary
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/veterinaries/create.js.erb
<%= render "veterinaries/partials/save" %>

app/views/veterinaries/delete.js.erb
$("#modal-veterinaries").html("<%= j(render 'veterinaries/partials/delete') %>")
$("#modal-veterinaries").modal("show")

app/views/veterinaries/destroy.js.erb
<%= render "veterinaries/partials/save" %>

app/views/veterinaries/edit.js.erb
$("#modal-veterinaries").html("<%= j(render 'veterinaries/partials/edit') %>");
$("#modal-veterinaries").modal({backdrop: 'static', keyboard: false});
$("#modal-veterinaries").modal("show");

app/views/veterinaries/filter.js.erb
$("#modal-veterinaries").html("<%= escape_javascript(render 'veterinaries/partials/filter_form') %>")
$("#modal-veterinaries").modal({backdrop: 'static', keyboard: false})
$("#modal-veterinaries").modal("show")

app/views/veterinaries/index.html.erb
 
<div class="row">
  <div class="col-lg-12">
    <div class="card">
      <div class="header">
        <h4 class="title"><i class="pe-7s-eyedropper"></i> Veterinarios</h4>
        <p class="category"><%= notice %></p>
      </div> 
      <div class="content">  
       
        <%= link_to  new_veterinary_path , {remote:true, class: "fcbtn btn btn-success btn-1e" } do %>
        <i class="icon-plus"></i>
        <span>Nuevo</span>
        <%end%>

        <%= link_to  filter_veterinaries_path , {remote:true, class: "fcbtn btn btn-primary btn-1e" } do %>
        <i class="icon-search"></i>
        <span>Buscar</span>
        <%end%>

        
        <table class="table">
          <thead>
            <tr>
              <th> <%= t('veterinaries.id')%> </th>
              <th><%= t('veterinaries.name')%></th>
              <th><%= t('veterinaries.email')%></th>
              <th><%= t('veterinaries.created_at')%></th> 
              <th colspan="3">Acciones</th>
            </tr> 
          </thead>
          <tbody class="veterinaries-table-index">
            <%= render 'veterinaries/partials/index'%>
          </tbody>
          <tfoot>
            <td colspan="7">
              <div class="text-right">
                <ul class="pagination">
                  <%= paginate @veterinaries %>
                </ul>
              </div>
            </td>
          </tfoot>
        </table>  
      </div>
    </div>
  </div>
</div> 

<div id="modal-veterinaries" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>

app/views/veterinaries/index.js.erb
$(".veterinaries-table-index").html("<%= escape_javascript(render 'veterinaries/partials/index') %>")
$("#modal-veterinaries").modal({backdrop: 'static', keyboard: false})
$("#modal-veterinaries").modal("hide")

app/views/veterinaries/new.js.erb
$("#modal-veterinaries").html("<%= j(render 'veterinaries/partials/new') %>")
$("#modal-veterinaries").modal("show")
//$('#modal-veterinaries').keypress(function(event){if (event.keyCode == 10 || event.keyCode == 13) event.preventDefault();});
$('select').select2();

app/views/veterinaries/partials/_delete.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
	<h3 class="modal-title">Eliminar</h3>
</div>
<div class="modal-body">
	<ul class="errors"></ul>
	 Desea eliminar <b><%= @veterinary.user.name %></b>?
</div>
<div class="modal-footer">
	<%= link_to t('veterinaries.confirm_delete'), veterinary_path(@veterinary), method: :delete, class: "btn btn-danger waves-effect", data: { turbolinks: false } %>
	 <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">No</button>
</div>
</div>
</div>

app/views/veterinaries/partials/_edit.html.erb
<div class="modal-dialog">
 	<div class="modal-content">
 		<div class="modal-header">
 			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
 			<h4 class="modal-title" id="myModalLabel">Editar  </h4>
 		</div>
 		<%= render 'veterinaries/partials/form' %>
 	</div>
 	<!-- /.modal-content -->
</div>

app/views/veterinaries/partials/_fields_show.html.erb
<div class="col-lg-6">

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><%= t('veterinaries.veterinary')%></h3>
  </div>
  <div class="panel-body">
	<p id="notice">
	<%= notice %>
</p>

<p>
  <strong>Company name:</strong>
  <%= @veterinary.name %>
</p>


<p>
  <strong>Description:</strong>
  <%= @veterinary.description %>
</p>

</p>

 
<%= link_to 'Edit', edit_veterinary_path(@veterinary) %> 
 
  	</div>
</div>

</div>

app/views/veterinaries/partials/_filter_form.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h4 class="modal-title" id="myModalLabel">Búsqueda</h4>
			<h5>Ingrese los parámetros de su búsqueda</h5>
		</div>
		<%= form_tag veterinaries_path ,method: :get ,remote:true, class: "form-horizontal form-material" do %>
		<div class="modal-body">
			<div class="form-group">
				<div class="col-md-12 m-b-20"> 
				  <label class="col-md-12"><%= t("veterinaries.name")%></label>
				  <div class="col-md-12">
				  	<%= search_field_tag  "q[name_cont]",nil,class: "form-control", placeholder: 'Nombre' %>
				  </div>
				</div>
				
				<div class="col-md-12 m-b-20"> 
				  <label class="col-md-12"><%= t("veterinaries.description")%></label>
				  <div class="col-md-12">
				  	<%= search_field_tag "q[description_cont]",nil,class: "form-control" , placeholder: 'Descripción' %>
				  </div>
				</div>
			
			</div>
		</div>
		<div class="modal-footer">
			<%= submit_tag 'Buscar',class: 'btn btn-info waves-effect' %> 
			<button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancelar</button>
		</div>
		<% end %>
	</div>
	<!-- /.modal-content -->
</div>

app/views/veterinaries/partials/_form.html.erb
<%= form_for @veterinary,remote: true, html: { class: "form-horizontal form-material",role: "form" } do |f| %>		
<div class="modal-body">		
	<div class="form-group"> 
		<div style="background-color:red; color:white; font-weight:bold;">		
			<ul class="errors"></ul>		
		</div>		


		<%= f.fields_for :user do |ff| %>
		<div class="col-md-12 m-b-20"> 
			<label class="col-md-12"><%= t("users.name")%></label>
			<div class="col-md-12">
				<%= ff.text_field :name, class: "form-control"   %>
			</div>  
		</div> <hr>
		<div class="col-md-12 m-b-20"> 
			<label class="col-md-12"><%= t("users.lastname")%></label>
			<div class="col-md-12">
				<%= ff.text_field :lastname, class: "form-control" %>
			</div>  
		</div>
		<hr>	
		<%if @veterinary.user.new_record?%>
		<div class="col-md-12 m-b-20"> 
			<label class="col-md-12"><%= t("users.email")%></label>
			<div class="col-md-12">
				<%= ff.text_field :email, class: "form-control"   %>
			</div>
		</div>
		<hr>
		
		<div class="col-md-12 m-b-20"> 
			<label class="col-md-12"><%= t("users.password")%></label>
			<div class="col-md-12">
				<%= ff.password_field :password, class: "form-control"   %>
			</div>
		</div> <hr>
		<div class="col-md-12 m-b-20"> 
			<label class="col-md-12"><%= t("users.password_confirmation")%></label>
			 
				<%= ff.password_field :password_confirmation, class: "form-control"   %>
			 
		</div> 
		<hr> 
		<%end%>
		<% end %>
		<hr>
		<div class="col-md-12 m-b-20"> 
			<label class="col-md-12"><%= t("users.clinic")%></label>
			<div class="col-md-12">
				<%= f.text_field :clinic, class: "form-control"   %>
			</div>  
		</div>
		<hr>
		<div class="col-md-12 m-b-20"> 
			<label class="col-md-12"><%= t("users.address")%></label>
			<div class="col-md-12">
				<%= f.text_field :address, class: "form-control"   %>
			</div>  
		</div>
		<hr>
		<div class="col-md-12 m-b-20"> 
			<label class="col-md-12"><%= t("users.phone")%></label>
			<div class="col-md-12">
				<%= f.text_field :phone, class: "form-control"   %>
			</div>  
		</div>
		<hr>

		<div class="col-md-12 m-b-20"> 
			<label class="col-md-12"><%= t("users.web_site")%></label>
			<div class="col-md-12">
				<%= f.text_field :web_site, class: "form-control"   %>
			</div>  
		</div>
		<hr>
		
		
	</div>		 	
</div>		
<div class="modal-footer">		
	<%=f.submit 'save',class: 'btn btn-info waves-effect' %> 		
	<button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cancelar</button>
</div>		
<% end %>

app/views/veterinaries/partials/_index.html.erb
<% @veterinaries.each do |veterinary| %>
<tr>
	<td><%= veterinary.id %></td>
	<td><%= veterinary.user.name %> <%= veterinary.user.lastname %></td> 
	<td><%= veterinary.user.email %></td> 
	<td><%= veterinary.created_at %></td> 
 	
	 <td> 
        <%=link_to veterinary, :class => "btn btn-small btn-primary", remote: true do %>
          <i class="btn-icon-only icon-search"> </i>
        <%end%> 
         <%= link_to edit_veterinary_path(veterinary), :class => "btn btn-small btn-warning", remote:true do %>
          <i class="btn-icon-only icon-pencil"> </i>
        <%end%>
        
         <%=link_to veterinary_delete_path(veterinary), :class => "btn btn-small btn-danger", remote:true  do %>
           <i class="btn-icon-only icon-trash"> </i>
        <%end%> 
    </td>
 

 	 

</tr>
<% end.empty? and begin %>
<h1>No  se  han encontrado  resultados</h1>
<% end %>

app/views/veterinaries/partials/_new.html.erb
<div class="modal-dialog">
 	<div class="modal-content">
 		<div class="modal-header">
 			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
 			<h4 class="modal-title" id="myModalLabel"><%= t('veterinaries.new_veterinary') %></h4>
 		</div>
 		<%= render 'veterinaries/partials/form' %>
 	</div>
 	<!-- /.modal-content -->
</div> 

app/views/veterinaries/partials/_save.js.erb
$("ul.errors").html("")
<% if @veterinary.errors.any? %>
  <% @veterinary.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %> 
  $("#modal-veterinaries").animate({ scrollTop: 0 }, 'slow')
<% else %>
  $(".veterinaries-table-index").html("<%= j(render 'veterinaries/partials/index') %>")
  $("ul.msg").append($("<li />").html("<%= @msgResult %>"))
  $("#modal-veterinaries").modal("hide")
<% end %>

app/views/veterinaries/partials/_show.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
			<h4 class="modal-title" id="myModalLabel">Datos de la empresa</h4>
		</div>
		<div class="modal-body">
			<div class="form-group">
			  
				<div class="col-md-12 m-b-20">
					<div class="control-label"><strong><%= t("veterinary.name")%>:</strong>
						<p><%= @veterinary.user.name %> <%= @veterinary.user.lastname %></p>
					</div>
					
				</div>
				<!-- /.row -->
				<hr>
				<!-- .row -->
				<div class="col-md-12 m-b-20">
					<div class="control-label"><strong><%= t('user.email') %>:</strong>
						<p><%= @veterinary.user.email %></p> 

					</div>
					
				</div>
				<!-- /.row -->
               <hr>
				<div class="col-md-12 m-b-20">
					<div class="control-label"><strong><%= t('veterinary.clinic') %>:</strong>
						<p><%= @veterinary.clinic %> </p> 

					</div>
					
				</div>
				<hr>
				<div class="col-md-12 m-b-20">
					<div class="control-label"><strong><%= t('veterinary.address') %>:</strong>
						<p><%= @veterinary.address %> </p> 

					</div>
					
				</div>
				<hr>
				
				<hr>
				<div class="col-md-12 m-b-20">
					<div class="control-label"><strong><%= t('veterinary.phone') %>:</strong>
						<p><%= @veterinary.phone %> </p> 

					</div>
					
				</div>
				<hr>		
 
			</div>
		</div>
		<div class="modal-footer"> 
			<button type="button" class="btn btn-default waves-effect" data-dismiss="modal">Cerrar</button>
		</div>
	</div>
	<!-- /.modal-content -->
</div>

app/views/veterinaries/show.js.erb
$("#modal-veterinaries").html("<%= escape_javascript(render 'veterinaries/partials/show') %>")
$("#modal-veterinaries").modal({backdrop: 'static', keyboard: false})
$("#modal-veterinaries").modal("show")

app/views/veterinaries/update.js.erb
<%= render "veterinaries/partials/save" %>